apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: dXNlcm5hbWU=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: dG9kb19kYg==
  DB_USER: dG9kb191c2Vy
  DB_PASSWORD: ZGJfcGFzc3dvcmQ=
  DB_HOST: mysql-0.mysql
