apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          envFrom:
            - secretRef:
                name: app-secret
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              subPath: init.sql
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "--silent"
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "--silent"
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  initContainers:
    - name: mysql-init
      image: busybox
      command: [ "sh", "-c", "cp /tmp/init.sql /docker-entrypoint-initdb.d/" ]
      volumeMounts:
        - name: init-sql
          mountPath: /tmp
  volumes:
    - name: init-sql
      configMap:
        name: init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
